version: '3.8'
services:
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_USER: belen
      POSTGRES_PASSWORD: belen
      POSTGRES_DB: belen_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgresql
